apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-service-account-role
  namespace: app
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-service-account-role-binding
  namespace: app
subjects:
- kind: ServiceAccount
  name: worker-service-account
  namespace: app
roleRef:
  kind: Role
  name: worker-service-account-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker-service-account
      containers:
      - name: worker
        image: demo/worker:{{GIT_COMMIT}}
        imagePullPolicy: IfNotPresent
        args:
        - --redis=rfs-redis:26379
        - --redis-master-name=mymaster
        - --api=http://api:9999
        - --job-namespace=app
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
